### PR TITLE
First draft of PR Draft 2

### PR DESCRIPTION
**Pull request by talltree**

### CODE REVIEW

**Comment by darrellodonnell** [comment]
That's one heck of a commit. I am happy to approve the PR.

**Comment by talltree** [comment]
@wenjing On the TSWG call this morning, I explained that I finished all the revisions to this spec for the PR2 draft. But I still had TOC formatting issues. Thanks to Andor's help cleaning up the TOC issue, this is now ready for your review. NOTE: with the new Spec-Up-managed TOC, one task that remains is to update all the internal references. I'm happy to do that if everything else looks good to you. 

image

**Comment by andorsk** [comment]
Just to clarify process here @wenjing so you can make edits:

1. yarn install
2. yarn edit <- for live edits

In another terminal

1. cd docs
2. http-server ( I used https://www.npmjs.com/package/http-server but there are many )
3. Go to http://localhost:8080

edit spec.md file in the spec folder. My setup for editing stuff below:

image

Idea is to send PR against talltree (Drummonds) remote and then he can merge it in as one cleaned up PR together.

**Comment by wenjing** [comment]
@talltree @andorsk Looking into this in the next few days...

**Comment by wenjing** [comment]
> @talltree @andorsk Looking into this in the next few days...

I have finished my quick review and identified around half a dozen issues, in addition to diagram label updates and other minor edits. Before I try to edit on the PR however, let me try to get a clear consensus on a few substantive issues here first:

(1) The use of 'authenticity' and 'integrity'

There was an old debate around which variant of definitions to use. The TSP spec eventually decided to use 'authenticity' to mean BOTH authentic identifier and integrity of the message. This definition IS used in the tech arch as well in the "Design Goals" section. That's good. BUT, later in the "Messages" section, it listed "Integrity" separately from "authenticity". I believe we should stick to the expansive definition of 'Authenticity' throughout, and merge 'Integrity' to 'Authenticity' and remove 'Integrity' in the later list. This modification will make this spec consistent with itself and with the TSP spec.

If such discrepancy exists in the terms wiki, we should make some changes there too. (Of course we could note there that we have chosen this way while others may use them differently so the readers are aware.)

(2) Privacy

The term is defined in this doc in probably misleading. In "Design Goals", it currently says "will the expectations of each party with respect to usage of shared information be honored by the other parties?". I don't believe the ToIP stack or stacks directly tackle this broader problem. The TSP spec has taken a much more precise approach of defining privacy as "Metadata privacy" and its solution is to protect against tracking & correlations. (Note that content privacy is already named confidentiality) While this spec CAN have broader definitions because it should include capabilities introduced in the upper layers in trust tasks or trust applications, I still think the current phrasing is not accurate. I would bring it back to "Metadata privacy" and add a sentence to suggest that additional notions of privacy can be built with trust tasks and applications.

(3) SCID and XVID
These are new and a good way to classify VIDs, but the wording is a little too complex and tied to specifics. If OK with everyone, I'd write something more abstract. We really just need to say one type is self-contained, the other needs an external entity. Then we list an example or two. I'll propose some text.

Let me know if we are all on the same page before I try to propose a change.

**Comment by wenjing** [comment]
> Just to clarify process here @wenjing so you can make edits:
> 
> 1. yarn install
> 2. yarn edit <- for live edits
> 
> In another terminal
> 
> 1. cd docs
> 2. http-server ( I used https://www.npmjs.com/package/http-server but there are many )
> 3. Go to http://localhost:8080
> 
> edit spec.md file in the spec folder. My setup for editing stuff below:
> 
> image
> Idea is to send PR against talltree (Drummonds) remote and then he can merge it in as one cleaned up PR together.

@andorsk A little uncertain what would be an easy way to edit on the PR - can you provide a list of git steps, just to be sure?

**Comment by talltree** [comment]
@wenjing This is in reply to your questions [above](https://github.com/trustoverip/tswg-tech-architecture-spec/pull/6#issuecomment-2334747562).



> (1) The use of 'authenticity' and 'integrity'
> 
> There was an old debate around which variant of definitions to use. The TSP spec eventually decided to use 'authenticity' to mean BOTH authentic identifier and integrity of the message. This definition IS used in the tech arch as well in the "Design Goals" section. That's good. BUT, later in the "Messages" section, it listed "Integrity" separately from "authenticity". I believe we should stick to the expansive definition of 'Authenticity' throughout, and merge 'Integrity' to 'Authenticity' and remove 'Integrity' in the later list. This modification will make this spec consistent with itself and with the TSP spec.
> 
> If such discrepancy exists in the terms wiki, we should make some changes there too. (Of course we could note there that we have chosen this way while others may use them differently so the readers are aware.)

Yes, I was thinking about this as I did the edits. I didn't know whether we decided to keep "integrity" or not. However I'm 100% on board with your proposed fix. If you want to fix this in the PR, I would be happy take care of editing the ToIP Glossary entries for "authenticity" and "integrity" to align with this if we have consensus on this revision. Does anyone else object?



> (2) Privacy
> 
> The term is defined in this doc in probably misleading. In "Design Goals", it currently says "will the expectations of each party with respect to usage of shared information be honored by the other parties?". I don't believe the ToIP stack or stacks directly tackle this broader problem. The TSP spec has taken a much more precise approach of defining privacy as "Metadata privacy" and its solution is to protect against tracking & correlations. (Note that content privacy is already named confidentiality) While this spec CAN have broader definitions because it should include capabilities introduced in the upper layers in trust tasks or trust applications, I still think the current phrasing is not accurate. I would bring it back to "Metadata privacy" and add a sentence to suggest that additional notions of privacy can be built with trust tasks and applications.

100% agree here too. This is exactly the kind of alignment question that I hoped you would call out so that this spec and the TSP spec were aligned. In fact, if we just stick with the term "metadata privacy" in this spec, I can also add that to the ToIP Glossary as currently we don't have an entry for "privacy" by itself (just as we don't have one for "security" by itself) because by themselves those terms are too broad.



> (3) SCID and XVID
> These are new and a good way to classify VIDs, but the wording is a little too complex and tied to specifics. If OK with everyone, I'd write something more abstract. We really just need to say one type is self-contained, the other needs an external entity. Then we list an example or two. I'll propose some text.

I am also fine with this. If you need to edit the diagram itself, the source is [here](https://docs.google.com/presentation/d/1lqaidE8hBA7Ona_-TnTCiOeLhCVRf_1m8ujBMuYtl7k/edit?pli=1#slide=id.g2f8195893c1_0_0).

**********
Please let us know when you are ready for further review. Thanks!

**Comment by talltree** [comment]
@wenjing Also, the one other outstanding action item is to update all the internal references to reference the Spec-Up headings instead of the Markdown-style internal references that you used in PR1. Are you going to do this, or do you want me or another volunteer to do it after you are done with your edits?

**Comment by wenjing** [comment]
> @wenjing Also, the one other outstanding action item is to update all the internal references to reference the Spec-Up headings instead of the Markdown-style internal references that you used in PR1. Are you going to do this, or do you want me or another volunteer to do it after you are done with your edits?

@talltree I could make the above mentioned changes. And also all figures that marked with my name (ie I have the source). Plus a few minor ones that I have noted down but pretty sure won't be problematic. @andorsk is suggesting to make edits to your PR, then you could add your own edits before merge the PR. I'll try to do it on Monday.

**Comment by wenjing** [comment]
I just realized that this is a brand new repo - this will cause us to lose all history of the version 1.0 of the spec. I think it's essential we maintain the history - version 2's changes are not substantial other than the new stack diagrams. With a new repo we would not be able to see the evolution and where specific changes are made for what reasons. I'd like to request the PR be submitted to the original repo.

**Comment by andorsk** [comment]
Good callout, but if you're referring to [TechArch](https://github.com/trustoverip/TechArch) that repo was publicly archived on March 5 as read only ( I don't know context on why, just that it is ). 

Do you know why it was archived?

**Comment by wenjing** [comment]
I have no idea either, but I just unarchived it. I might be for changing the name (to have uniform repo names) but I think the interests of keeping the history is far more important to us. It should be read-write now.

**Comment by andorsk** [comment]
@wenjing The last commit on TechArch was 2 years ago. The last commit on this repo is 4 months ago.

- New: https://github.com/trustoverip/tswg-tech-architecture-spec/commits/main/  
- Old: https://github.com/trustoverip/TechArch/commits/main/

I totally understand the need to preserve history ( big fan of it ), but given a historical decision to deprecate the TechArch repo and move to tswg-tech-architecture repo, my vote is to put it here.

If I had to take a guess, my gut is TechArch needed to be renamed, but renaming a repo can cause issues with people anchoring on it. (I've seen this). So, it was archived and a new repo was made with a new name. Unfortunately, I don't see a record of this decision.

A solution here that may be a compromise: 

1. Add a note in the README of https://github.com/trustoverip/TechArch declaring that it has been moved to https://github.com/trustoverip/tswg-tech-architecture-spec. Ideally, if we can understand the decision around this that would be good. 
2. Put it back into archive. 
3. Merge PR here, with even a mention on the README that old history is on TechArch. 

This preserves the history/linkage between repos and still respects historical decisions.

Thoughts?

**Comment by andorsk** [comment]
Referenced and repulled at https://github.com/trustoverip/TechArch/pull/91

**Pull request closed without merging**
